### ISSUE TITLE
Feature Request: Option to disable damage immunity for melee hits to improve co-op experience

### ISSUE THREAD

**Issue by SodiumShine** [Fuzss/goldenagecombat#16]
You already have an option for disabling damage immunity with projectiles, I think this would go well with certain configurations.
It would definitely make co-op combat much greater since i-frames in vanilla currently make multiple players fighting the same enemy extremely annoying, almost pointless in fact.

**Comment by Fuzss** [comment]
Hmm, this is actually a rather complex change from vanilla. 

Just not setting damage immunity for player attacks doesn't work, since that's the main purpose of the system to slow down the player. So implementing this effectively would require a per player damage immunity counter on every mob. Since damage immunity isn't just a single variable anyways (I think it's like three at least, since it also keeps track of the last damage amount and so on), so implementing this would require quite a bit of refactoring of vanilla code. 

I'm honestly not keen on doing something like this, but [this mod](https://www.curseforge.com/minecraft/mc-mods/better-hurt-timer) overhauls damage immunity anyways. I'm not sure how it handles your case, but if it doesn't it may still be worth talking to that dev instead.

**Comment by SodiumShine** [comment]
Better Hurt Timer doesn't support 1.18.2 and doesn't look like it's being actively developed.
I've been using [No Damage Immunity Reload](https://www.curseforge.com/minecraft/mc-mods/no-damage-immunity-reload). It works _okay_ in conjunction with Golden Age Combat, but there's some issues like with how knockback is handled. 

Regardless, thanks anyway!
